apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: login
    spec:
      containers:
        - image: docker.elastic.co/demos/workshop/observability/elastiflix-dotnet-login:8.9.0-10
          name: login
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
