apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server
          image: docker.elastic.co/demos/workshop/observability/elastiflix-node-server:8.9.0-10
          ports:
            - containerPort: 3001
          env:
            - name: API_ENDPOINT_FAVORITES
              value: favorite-java:5000
            - name: API_ENDPOINT_LOGIN
              value: login:80
            - name: ELASTICSEARCH_URL
              value: https://absa.es.us-central1.gcp.cloud.es.io
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: vAVGDFGedbToHQtpCDBLppef
            - name: THROW_NOT_A_FUNCTION_ERROR
              value: "false"
