apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: favorite-java
  name: favorite-java
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5000
  selector:
    io.kompose.service: favorite-java
